theory Fraction_Field_Applications
  imports
    Nagata_Lemmas
    "HOL-Algebra.Polynomial_Divisibility"
begin

section \<open>Constant-prime localization applications\<close>

text \<open>
  This theory packages the fraction-field side of the Isabelle port at the same
  level of abstraction as @{theory Polynomial_Applications}: it specializes
  Nagata's theorem to multiplicative sets generated by constant prime
  polynomials. The remaining concrete comparison with a polynomial ring over a
  fraction field can then be added on top of this interface.
\<close>

context domain
begin

lemma polynomial_prime_generated_constant_closure:
  assumes K: "subring K R"
    and A_sub: "A \<subseteq> K"
    and hprime: "\<And>q. q \<in> A \<Longrightarrow> ring_prime\<^bsub>K[X]\<^esub> [q]"
  shows
    "ring_prime_generated (K[X])
      (ring_mult_submonoid_closure (K[X]) ((\<lambda>q. [q]) ` A))"
proof (rule ring_prime_generated_mult_submonoid_closure[OF univ_poly_is_ring[OF K]])
  show "(\<lambda>q. [q]) ` A \<subseteq> carrier (K[X])"
  proof
    fix p
    assume p_in: "p \<in> (\<lambda>q. [q]) ` A"
    then obtain q where q_in: "q \<in> A" and p_def: "p = [q]"
      by blast
    have qK: "q \<in> K"
      using A_sub q_in by blast
    show "p \<in> carrier (K[X])"
      unfolding p_def sym[OF univ_poly_carrier] polynomial_def
      using qK by auto
  qed
  fix p
  assume "p \<in> (\<lambda>q. [q]) ` A"
  then obtain q where q_in: "q \<in> A" and p_def: "p = [q]"
    by blast
  show "ring_prime\<^bsub>K[X]\<^esub> p"
    unfolding p_def by (rule hprime[OF q_in])
qed

lemma zero_notin_polynomial_constant_closure:
  assumes K: "subring K R"
    and A_sub: "A \<subseteq> K"
    and hprime: "\<And>q. q \<in> A \<Longrightarrow> ring_prime\<^bsub>K[X]\<^esub> [q]"
  shows
    "\<zero>\<^bsub>K[X]\<^esub> \<notin> ring_mult_submonoid_closure (K[X]) ((\<lambda>q. [q]) ` A)"
proof -
  have "ring_prime_generated (K[X])
      (ring_mult_submonoid_closure (K[X]) ((\<lambda>q. [q]) ` A))"
    by (rule polynomial_prime_generated_constant_closure[OF K A_sub hprime])
  then show ?thesis
    by (rule zero_notin_submonoid_of_prime_generated)
qed

end

locale polynomial_constant_prime_localization =
  poly: nagata_localization "K[X]" "ring_mult_submonoid_closure (K[X]) ((\<lambda>q. [q]) ` A)" +
  base: domain R
  for R (structure) and K and A
begin

text \<open>
  Once a localization of @{text "K[X]"} at a constant-prime closure has been
  fixed, Nagata's theorem immediately reduces factoriality of @{text "K[X]"} to
  factoriality of that localization.
\<close>

lemma polynomial_factorial_of_localized_constant_primes_factorial:
  assumes K: "subring K R"
    and A_sub: "A \<subseteq> K"
    and noeth: "noetherian_domain (K[X])"
    and hprime: "\<And>q. q \<in> A \<Longrightarrow> ring_prime\<^bsub>K[X]\<^esub> [q]"
    and loc_fd: "factorial_domain poly.rec_rng_of_frac"
  shows "factorial_domain (K[X])"
  using poly.nagata_theorem[
      OF noeth base.polynomial_prime_generated_constant_closure[OF K A_sub hprime] loc_fd
    ] .

end

end
