theory Nagata_Factoriality
  imports
    Prime_Generated
    Nagata_Lemmas
    Polynomial_Applications
    Fraction_Field_Applications
    "HOL-Computational_Algebra.Polynomial"
begin

section \<open>Nagata-factoriality scaffolding\<close>

text \<open>
  Nagata's factoriality theorem descends unique factorization from a localization
  to the base ring under a prime-generated hypothesis on the multiplicative
  set.  The present entry now packages the prime-generated core, a wrapper
  layer over the AFP localization entry, and a record-based HOL-Algebra proof
  of both the prime-generated and prime-or-unit descent variants in
  @{text Nagata_Lemmas}.  The additional theory @{text Polynomial_Applications}
  now packages the record-based ``localize away X'' application for
  polynomial rings, leaving the remaining parity work with the companion Lean
  development concentrated in the concrete Laurent-polynomial and
  fraction-field identifications, cf.\ Nagata and Samuel.\<^cite>\<open>"Nagata1962"\<close> \<^cite>\<open>"Samuel1964"\<close>
\<close>

lemma prime_generated_constant_prime_polynomials:
  fixes A :: "'a :: semidom set"
  assumes "\<And>c. c \<in> A \<Longrightarrow> prime_elem c"
  shows "prime_generated (mult_submonoid_closure ((\<lambda>c. [:c:]) ` A))"
proof (rule prime_generated_mult_submonoid_closure)
  fix q
  assume "q \<in> (\<lambda>c. [:c:]) ` A"
  then obtain c where "c \<in> A" and q_def: "q = [:c:]"
    by blast
  from assms[OF \<open>c \<in> A\<close>] show "prime_elem q"
    unfolding q_def by (rule lift_prime_elem_poly)
qed

corollary zero_notin_constant_prime_polynomial_closure:
  fixes A :: "'a :: idom set"
  assumes "\<And>c. c \<in> A \<Longrightarrow> prime_elem c"
  shows "0 \<notin> mult_submonoid_closure ((\<lambda>c. [:c:]) ` A)"
proof -
  have "prime_generated (mult_submonoid_closure ((\<lambda>c. [:c:]) ` A))"
    using assms by (rule prime_generated_constant_prime_polynomials)
  then show ?thesis
    by (rule zero_notin_prime_generated[where S = "mult_submonoid_closure ((\<lambda>c. [:c:]) ` A)"])
qed

text \<open>
  The last corollary already reflects one of the key configurations in the Lean
  development: the multiplicative set generated by constant prime polynomials is
  prime-generated and therefore avoids zero.  This is the algebraic kernel of
  the fraction-field localization route to Nagata's theorem.
\<close>

text \<open>
  Separately, the theory @{text Localization_Interface} exposes an Isabelle/HOL
  wrapper around the AFP localization construction with lemmas for representative
  equality, numerator-denominator surjectivity, denominator rescaling,
  cross-multiplication in the domain case, units coming from both the
  multiplicative set and base-ring units, and injectivity of the canonical
  localization map under the usual domain hypotheses.  On top of that,
  @{text Nagata_Lemmas} proves the descent lemmas needed for Nagata's theorem,
  together with a record-based multiplicative-closure API
  @{thm [display] ring_prime_generated_mult_submonoid_closure} for the
  constant-prime submonoids used in the fraction-field route, culminating in
  theorem statements @{thm [display] nagata_theorem} and
  @{thm [display] nagata_theorem_of_prime_or_unit}.  The theory
  @{text Polynomial_Applications} then specializes this framework to the
  polynomial ring case by proving @{thm [display] polynomial_prime_X} over
  fields and the abstract away-X descent theorem
  @{thm [display] polynomial_factorial_of_localized_X_factorial}, while
  @{text Fraction_Field_Applications} packages the companion constant-prime
  closure theorem
  @{thm [display] polynomial_factorial_of_localized_constant_primes_factorial}.
\<close>

end
