theory Prime_Generated
  imports "HOL-Computational_Algebra.Factorial_Ring"
begin

section \<open>Prime-generated multiplicative sets\<close>

text \<open>
  This theory isolates the reusable combinatorial layer behind the companion Lean
  development of Nagata's factoriality theorem.  The full localization argument
  is intentionally left to later theories; here we focus on the multiplicative
  sets generated by prime elements and on the closure lemmas that do not depend
  on any localization API.
\<close>

definition avoids :: "'a :: comm_semiring_1 set \<Rightarrow> 'a \<Rightarrow> bool" where
  "avoids S p \<longleftrightarrow> (\<forall>s\<in>S. \<not> p dvd s)"

definition prime_generated :: "'a :: comm_semiring_1 set \<Rightarrow> bool" where
  "prime_generated S \<longleftrightarrow>
    (\<forall>s\<in>S. \<exists>M. (\<forall>q. q \<in># M \<longrightarrow> q \<in> S \<and> prime_elem q) \<and> prod_mset M = s)"

inductive_set mult_submonoid_closure :: "'a :: comm_monoid_mult set \<Rightarrow> 'a set" for A where
  one_closed: "1 \<in> mult_submonoid_closure A"
| generator: "a \<in> A \<Longrightarrow> a \<in> mult_submonoid_closure A"
| mult_closed:
    "a \<in> mult_submonoid_closure A \<Longrightarrow> b \<in> mult_submonoid_closure A \<Longrightarrow>
      a * b \<in> mult_submonoid_closure A"

definition powers_set :: "'a :: monoid_mult \<Rightarrow> 'a set" where
  "powers_set p = {x. \<exists>n. x = p ^ n}"

lemma prime_generatedI:
  assumes "\<And>s. s \<in> S \<Longrightarrow> \<exists>M. (\<forall>q. q \<in># M \<longrightarrow> q \<in> S \<and> prime_elem q) \<and> prod_mset M = s"
  shows "prime_generated S"
  using assms unfolding prime_generated_def by blast

lemma prime_generatedE:
  assumes "prime_generated S" "s \<in> S"
  obtains M where "(\<forall>q. q \<in># M \<longrightarrow> q \<in> S \<and> prime_elem q)" "prod_mset M = s"
  using assms unfolding prime_generated_def by blast

lemma prime_generated_powers_set:
  assumes "prime_elem p"
  shows "prime_generated (powers_set p)"
proof (rule prime_generatedI)
  fix s
  assume "s \<in> powers_set p"
  then obtain n where hs: "s = p ^ n"
    unfolding powers_set_def by blast
  have factors:
    "\<forall>q. q \<in># replicate_mset n p \<longrightarrow> q \<in> powers_set p \<and> prime_elem q"
  proof
    fix q
    show "q \<in># replicate_mset n p \<longrightarrow> q \<in> powers_set p \<and> prime_elem q"
    proof (cases n)
      case 0
      then show ?thesis
        by simp
    next
      case (Suc m)
      show ?thesis
      proof
        assume "q \<in># replicate_mset n p"
        from \<open>q \<in># replicate_mset n p\<close> have "n > 0 \<and> q = p"
          by (simp only: in_replicate_mset)
        with Suc have q_eq: "q = p"
          by simp
        have q_in_powers: "q \<in> powers_set p"
        proof -
          from q_eq have "q = p ^ Suc 0"
            by simp
          then show ?thesis
            unfolding powers_set_def by blast
        qed
        from q_eq assms have q_prime: "prime_elem q"
          by simp
        from q_in_powers q_prime show "q \<in> powers_set p \<and> prime_elem q"
          by blast
      qed
    qed
  qed
  show "\<exists>M. (\<forall>q. q \<in># M \<longrightarrow> q \<in> powers_set p \<and> prime_elem q) \<and> prod_mset M = s"
    by (rule exI[of _ "replicate_mset n p"]) (use factors hs in auto)
qed

lemma prime_generated_mult_submonoid_closure:
  assumes "\<And>q. q \<in> A \<Longrightarrow> prime_elem q"
  shows "prime_generated (mult_submonoid_closure A)"
proof (rule prime_generatedI)
  fix s
  assume "s \<in> mult_submonoid_closure A"
  then show
    "\<exists>M. (\<forall>q. q \<in># M \<longrightarrow> q \<in> mult_submonoid_closure A \<and> prime_elem q) \<and> prod_mset M = s"
  proof induction
    case one_closed
    show ?case
      by (rule exI[of _ "{#}"]) (auto intro: mult_submonoid_closure.one_closed)
  next
    case (generator a)
    show ?case
    proof (rule exI[of _ "{#a#}"])
      from generator assms show
        "(\<forall>q. q \<in># {#a#} \<longrightarrow> q \<in> mult_submonoid_closure A \<and> prime_elem q) \<and>
          prod_mset {#a#} = a"
        by (auto intro: mult_submonoid_closure.generator)
    qed
  next
    case (mult_closed a b)
    from mult_closed.IH(1) obtain M where
      M:
        "(\<forall>q. q \<in># M \<longrightarrow> q \<in> mult_submonoid_closure A \<and> prime_elem q)"
        "prod_mset M = a"
      by blast
    from mult_closed.IH(2) obtain N where
      N:
        "(\<forall>q. q \<in># N \<longrightarrow> q \<in> mult_submonoid_closure A \<and> prime_elem q)"
        "prod_mset N = b"
      by blast
    show ?case
    proof (rule exI[of _ "M + N"])
      from M N mult_closed show
        "(\<forall>q. q \<in># M + N \<longrightarrow> q \<in> mult_submonoid_closure A \<and> prime_elem q) \<and>
          prod_mset (M + N) = a * b"
        by (auto simp: prod_mset_Un)
    qed
  qed
qed

lemma zero_notin_prime_generated:
  assumes "prime_generated S"
  shows "(0 :: 'a :: semidom) \<notin> S"
proof
  assume "0 \<in> S"
  from assms and \<open>0 \<in> S\<close> obtain M where
    M: "(\<forall>q. q \<in># M \<longrightarrow> q \<in> S \<and> prime_elem q)" "prod_mset M = 0"
    by (rule prime_generatedE)
  from M(2) have "0 \<in># M"
    by simp
  with M(1) show False
    by auto
qed

end
